print('Enter the first number')
number1 = int(input())
print('Enter the second number')
number2 = int(input())
added_number = (int(number1) + int(number2))
multiplied_number = (int(number1) * int(number2))
print(str(number1))
print(str(number2))
print(str(added_number))
print(str(multiplied_number))